title: A
description: Test
permalink: none
timezone: Europe/London
baseurl: /moneypipe/
analytics:
    provider: google_analytics
comments:
    provider: disqus
    disqus_shortname: moneypipe
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
