title: Moneypipe
description: Test
permalink: none
timezone: Europe/London
analytics:
    provider: google_analytics
comments:
    provider: disqus
    disqus_shortname: moneypipe
    num_posts: 10
    colorscheme: light
    order: social
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
